### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#10]
**What version of this package are you using?**

2.1.0

**What operating system, Node.js, and npm version?**

N/A 

**What happened?**

```
  RangeError: Invalid time value
      at Date.toISOString (<anonymous>)
      at /home/christianbundy/oasis/src/pages/models/post.js:90:63
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Promise.all (index 0)
      at async Object.fromThread (/home/christianbundy/oasis/src/pages/models/post.js:392:25)
      at async threadPage (/home/christianbundy/oasis/src/pages/thread.js:9:20)
      at async /home/christianbundy/oasis/src/app.js:105:18
      at async /home/christianbundy/oasis/node_modules/koa-mount/index.js:52:26
```

**What did you expect to happen?**

No errors.

**Are you willing to submit a pull request to fix this bug?**

:heavy_check_mark:

**Comment by christianbundy** [comment]
NOPE.

Turns out this is actually coming from when we're missing a message, because the message object is:

```
[ value: { meta: { thread: [Object], md: [Object] } } ]
```

**Comment by christianbundy** [comment]
No consistent repro, I'm going to close this again until it comes back. :cry:
