### ISSUE TITLE
Key not found in database [@C/zyw6xOd/QIcTLuZKZcrMoMmTwMfQs0u0rWEhNksgw=.ed25519,31]

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#12]
**What version of this package are you using?** 2.1.2

**What operating system, Node.js, and npm version?** N/A

**What happened?**

```
could not retrive msg: Error [NotFoundError]: Key not found in database [@C/zyw6xOd/QIcTLuZKZcrMoMmTwMfQs0u0rWEhNksgw=.ed25519,31]
    at /home/christianbundy/src/oasis/node_modules/level-packager/node_modules/levelup/lib/levelup.js:169:15
    at /home/christianbundy/src/oasis/node_modules/encoding-down/index.js:50:21
```

:man_shrugging: 

```console
$ npm ls levelup
@fraction/oasis@2.1.2 /home/christianbundy/src/oasis
└─┬ @fraction/flotilla@1.0.2
  ├─┬ ssb-blobs@1.2.2
  │ └─┬ level@5.0.1
  │   └─┬ level-packager@5.0.3
  │     └── levelup@4.2.0 
  └─┬ ssb-invite@2.1.3
    └─┬ level-sublevel@6.6.5
      └── levelup@0.19.1
```

Looks like an ssb-blobs thing, but I don't know why it'd be looking for a feed ID in the database *or* which page is doing this.

**What did you expect to happen?**

No error.

**Are you willing to submit a pull request to fix this bug?**

Yes.

**Comment by christianbundy** [comment]
```console
$ grep -R 'could not retrive msg'
node_modules/epidemic-broadcast-trees/index.js:        console.log('could not retrive msg:', err)
```

wat

**Comment by christianbundy** [comment]
Closing in favor of upstream bug report: https://github.com/dominictarr/epidemic-broadcast-trees/issues/30
