### ISSUE TITLE
Add user-friendly error message when localhost port is already taken

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#129]
**What's the problem you want solved?**
If the port is already taken by Oasis or some other process, you get this error:

```
  oasis Listening on http://localhost:3000/ +0ms
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1306:16)
    at listenInCluster (net.js:1354:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1493:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1333:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000
}
```

**Is there a solution you'd like to recommend?**
Show a more friendly message like

```
Error: another server is already running at http://localhost:3000.
It might be another copy of Oasis or another program on your computer.
You can run Oasis on a different port number with this option:
    oasis --port 3001
```

**Comment by christianbundy** [comment]
Yes! This would be rad, and probably super simple. We'd just need to wrap the `http.listen()` in a `try {} catch(e) {}` and as long as `e.code` (or `e.type`?) is "EADDRINUSE" we can show this error instead of the stacktrace.

**Comment by christianbundy** [comment]
Just tried the above method and it didn't work. Looks like there are some shenanigans afoot.
