### ISSUE TITLE
Oasis crashes ungracefully when connecting to an sbot without ssb-backlinks

### ISSUE THREAD

**Issue by sbillig** [fraction/oasis#385]
## What's the problem you want solved?

Oasis crashes with this stack trace when connecting to an ssb-server that doesn't have ssb-backlinks installed:

```
  oasis Connected to existing Scuttlebutt service over TCP socket +0ms
TypeError: Cannot read property 'read' of undefined
    at getMessages (/Users/sean/code/oasis/src/models.js:348:34)
    at Object.mentionsMe (/Users/sean/code/oasis/src/models.js:614:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async mentions (/Users/sean/code/oasis/src/index.js:554:24)
    at async /Users/sean/code/oasis/src/index.js:558:16
    at async middleware (/Users/sean/code/oasis/src/index.js:802:7)
    at async /Users/sean/code/oasis/src/index.js:780:5
    at async /Users/sean/code/oasis/src/index.js:775:5
    at async /Users/sean/code/oasis/src/http.js:29:5
    at async /Users/sean/code/oasis/node_modules/koa-mount/index.js:52:26
/Users/sean/code/oasis/src/index.js:107
    throw err;
    ^

Error: ssb-tangle require ssb-backlinks to be installed
    at Timeout._onTimeout (/Users/sean/code/oasis/node_modules/ssb-tangle/index.js:20:34)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

## Is there a solution you'd like to recommend?

Check for required ssb-server plugins, add them(?) or fail gracefully if not found.

**Comment by christianbundy** [comment]
True, thanks for pointing this out. 

One option we have is to use client-side plugins, where Oasis can connect to any SSB service that implements `get()`, `createLogStream()`, and `createSequenceStream()`, and we could [hypothetically] run Oasis on the Go or Rust implementations. There are basically three problems:

- **The Oasis views are dependent on the order of the logs.** If we remember "I've seen the first 1000 messages" and someone switches from the JS implementation to the Rust implementation, those messages might be in a different order and totally bone us. Maybe we could cache a few  (sequence number, message key) pairs and check those on server startup to make sure the log is in the same order that we last saw it?
- **We might need to duplicate our views.** Since Patchwork/etc use the views from `~/.ssb/flume` then we wouldn't want to put Oasis views there unless we're 100% sure that they're based on `~/.ssb/flume/log.offset`.
- **It's [very slow](https://github.com/ssbc/ssb-db/pull/275#issuecomment-561354178).** If you use a Unix socket with noauth then it takes ~14% longer, but if you're using TCP + SHS it takes like 450% longer.

Secret-Stack is such a pain point, I wish we could just `require()` the libraries we need and not have to worry about which capabilities the server has.

:man_shrugging:
