### ISSUE TITLE
Error: stream is closed

### ISSUE THREAD

**Issue by jedahan** [fraction/oasis#40]
When opening oasis from systemctl --user start oasis, it fails. manually running it is fine I think.

**What version of this package are you using?**
@latest

**What operating system, Node.js, and npm version?**
debian testing, node v12.14.0, npm 6.13.4

**What happened?**
I cannot view localhost:4515 - this is the error:
```
Error: stream is closed
    at /home/micro/.config/npm/lib/node_modules/@fraction/oasis/node_modules/muxrpc/index.js:45:25
    at remoteCall (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/node_modules/muxrpc/remote-api.js:40:19)
    at obj.<computed> (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/node_modules/muxrpc/remote-api.js:25:18)
    at /home/micro/.config/npm/lib/node_modules/@fraction/oasis/src/pages/models/lib/cooler.js:71:15
    at new Promise (<anonymous>)
    at Object.read (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/src/pages/models/lib/cooler.js:70:12)
    at Object.popular (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/src/pages/models/post.js:438:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async publicPopularPage (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/src/pages/public-popular.js:8:20)
```

**What did you expect to happen?**
to be able to see oasis

**Are you willing to submit a pull request to fix this bug?**
yes

**Comment by jedahan** [comment]
funny enough, removing `--no-open` from the args fixed it???

**Comment by christianbundy** [comment]
I'm not sure what causes this, but I experience it too. Usually just `systemctl --user restart oasis` resolves the problem. This would be resolved if the client could auto-reconnect, but we should probably add auto-restart to the server as well.

It looks like Patchbay [uses](https://github.com/ssbc/patchbay/blob/2f4c42595edc51adade0579bacf15063251d7367/modules_core/sbot.js) pull-reconnect for this.
