### ISSUE TITLE
oasis crash

### ISSUE THREAD

**Issue by zicmama** [fraction/oasis#415]
## What's the problem you want solved?
```
fred@rec:~/workspace/astroport/zen$ oasis --allow-host oasis.astroport.com
  oasis No configuration file found at /home/fred/.config/oasis/default.json, using built-in default values. +0ms
  oasis Listening on http://localhost:3000 +10s
  oasis Starting Scuttlebutt service +0ms
ssb-friends: stream legacy api used
server error, from net:82.64.191.57:40442~shs:
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at Socket.Writable.write (_stream_writable.js:322:17)
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/stream-to-pull-stream/index.js:63:30
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-cat/index.js:35:13
    at callback (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-pushable/index.js:84:5)
    at Object.push [as write] (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-pushable/index.js:44:7)
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/secret-handshake/protocol.js:103:19
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/secret-stack/plugins/shs.js:54:17
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/ssb-invite/index.js:67:16
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/level-sublevel/shell.js:101:15
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/level-sublevel/nut.js:121:19
server error, from net:67.38.20.120:49543~shs:
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at Socket.Writable.write (_stream_writable.js:322:17)
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/stream-to-pull-stream/index.js:63:30
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-cat/index.js:35:13

...
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/level-sublevel/nut.js:121:19
ssb-friends: get legacy api used
could not retrive msg: Error [NotFoundError]: Key not found in database [@unpYPUpx14PBNFFEQ+0916giJzmK5jaH0lO+zo8QAZw=.ed25519,47]
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/levelup/lib/levelup.js:188:15
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/encoding-down/index.js:75:21
could not retrive msg: Error [NotFoundError]: Key not found in database [@MRiJ+CvDnD9ZjqunY1oy6tsk0IdbMDC4Q3tTC8riS3s=.ed25519,2789]
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/levelup/lib/levelup.js:188:15
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/encoding-down/index.js:75:21
server error, from net:86.201.10.62:53018~shs:
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at Socket.Writable.write (_stream_writable.js:322:17)
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/stream-to-pull-stream/index.js:63:30
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-cat/index.js:35:13
...
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/level-sublevel/nut.js:121:19
server error, from net:167.172.220.62:40692~shs:
Error: stream ended with:64 but wanted:112
    at drain (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-reader/index.js:43:26)
...
    at Socket.<anonymous> (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error replicating with @ennK62KwH3KfitZAgeJMwjlD2h4Z2UIycuVCxPeaUFI=.ed25519:
   Error: method:createHistoryStream is not in list of allowed methods
    at Function.perms.pre (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/muxrpc/permissions.js:88:14)
    at Object.<anonymous> (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/muxrpc/local-api.js:35:21)
    at PacketStreamSubstream.stream.read (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/muxrpc/stream.js:69:23)
    at PacketStream._onstream (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/packet-stream/index.js:228:11)
    at PacketStream.write (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/packet-stream/index.js:135:41)
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/muxrpc/pull-weird.js:56:15
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/pull-reader/index.js:39:14)
Aborted
```

Hope there is enough report for you to understand what's going wrong.

**Comment by christianbundy** [comment]
Thanks for posting your bug report here. Does this happen each time that you try to use Oasis? 

I'm a bit confused, because I don't recognize any of those as errors that would cause a crash. Is there any more info you could maybe add about how the app is configured or the environment that it's running in?

**Comment by christianbundy** [comment]
It looks like maybe some of the problems were coming from the invite code, were you trying to redeem an invite during this crash?

**Comment by christianbundy** [comment]
Just reproduced the level-sublevel problem on my Android device (running via Termux). I'll move "rip level-sublevel out of our dependency tree" higher up my to-do list.

**Comment by zicmama** [comment]
I am happy you undestood what could have been wrong.
I was doing nothing special on the Pub, it didn't happen again.
It thought, it was in the network request handling?
