### ISSUE TITLE
Crash: Syntax error when receiving SIP invite

### ISSUE THREAD

**Issue by zicmama** [fraction/oasis#418]
As I understand, oasis crashes when it receives an INVITE from another protocol (SIP?!)

```
server error, from net:35.187.98.101:3319~shs:
Error: shs.server: client sent invalid challenge (phase 1), possibly they tried to speak a different protocol or had wrong application cap
    at Object.cb (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/secret-handshake/protocol.js:89:30)
    at drain (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-reader/index.js:39:14)
    at more (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-reader/index.js:55:13)
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-reader/index.js:66:9
    at /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/pull-reader/index.js:20:7
    at drain (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/stream-to-pull-stream/index.js:135:5)
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/src/index.js:114
    throw err;
    ^

Error: Syntax error at line 1 col 1:

  INVITE sip:0019294040830@51.15.166.54:8008 SIP/2.0
  ^
Unexpected "I". Instead, I was expecting to see one of the following:

A character matching /[a-z]/ based on:
    name →  ● /[a-z]/ name$ebnf$1
    protocol →  ● name protocol$ebnf$1
    address →  ● protocol address$ebnf$1
    multiaddress →  ● address multiaddress$ebnf$1

    at Parser.feed (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/nearley/lib/nearley.js:317:27)
    at parse (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/multiserver-address/index.js:6:10)
    at Object.exports.decode (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/multiserver-address/index.js:13:10)
    at Object.exports.getKeyFromAddress (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/ssb-ref/index.js:177:33)
    at Socket.LAN.readLegacy (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/ssb-lan/lib/index.js:24:31)
    at Socket.emit (events.js:321:20)
    at Socket.<anonymous> (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/broadcast-stream/index.js:51:12)
    at Socket.emit (events.js:321:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8) {
  offset: 0,
  token: { value: I }
}

```

**Comment by christianbundy** [comment]
Thanks, that looks like an invalid invite to me. The bug is coming from an upstream dependency, I've made an issue here: https://github.com/ssbc/ssb-ref/issues/39

**Comment by georgeowell** [comment]
Is this bug still re-creatable? The upstream bug has been closed.

**Comment by georgeowell** [comment]
Is this issues till re-creatable? Something has been merged upstream and the upstream has been closed.

**Comment by georgeowell** [comment]
I think this could be closed and rolled into https://github.com/fraction/oasis/issues/422

**Comment by Powersource** [comment]
editing the other issue to include showing errors
