### ISSUE TITLE
Give feedback when using an invite code

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#422]
## What's the problem you want solved?
Using an invite code gives no feedback when it has succeeded.

## Is there a solution you'd like to recommend?
Show a message "Success!  You and the pub are now following each other.  You are now downloading the members of this pub - reload to see them trickle in over the next few minutes."

**Comment by cbleslie** [comment]
Nicety - Better for a UI polish milestone?

**Comment by georgeowell** [comment]
I managed to trigger a error by entering random data into the invite bar:

```
Error: non-error thrown: {"message":"Cannot read property 'remote' of null","name":"TypeError","stack":"TypeError: Cannot read property 'remote' of null\n    at Object.<anonymous> (/usr/local/lib/node_modules/@fraction/oasis/node_modules/ssb-invite/index.js:222:56)\n    at apply (/usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc-validation/index.js:197:15)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc-validation/index.js:86:14)\n    at Object.hooked (/usr/local/lib/node_modules/@fraction/oasis/node_modules/hoox/index.js:10:15)\n    at Object.localCall (/usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc/local-api.js:31:29)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc/local-api.js:37:22)\n    at Object.request (/usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc/stream.js:48:17)\n    at PacketStream._onrequest (/usr/local/lib/node_modules/@fraction/oasis/node_modules/packet-stream/index.js:161:17)\n    at PacketStream.write (/usr/local/lib/node_modules/@fraction/oasis/node_modules/packet-stream/index.js:134:41)\n    at /usr/local/lib/node_modules/@fraction/oasis/node_modules/muxrpc/pull-weird.js:56:15"}
    at Object.onerror (/usr/local/lib/node_modules/@fraction/oasis/node_modules/koa/lib/context.js:113:40)
    at onerror (/usr/local/lib/node_modules/@fraction/oasis/node_modules/koa/lib/application.js:163:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
