### ISSUE TITLE
Add support for peer invites

### ISSUE THREAD

**Issue by Powersource** [fraction/oasis#428]
## What's the problem you want solved?

Oasis only has support for oldschool [ssb-invites](https://github.com/ssbc/ssb-invite/) and not [ssb-peer-invites](https://github.com/ssbc/ssb-peer-invites). Peer invites has several advantages (the readme mentions a few of them).

## Is there a solution you'd like to recommend?

Add support for peer invites (keep support for old invites though). This would mean:
* The "Accept invite" field in the settings page also accepts peer invites.
* [optional?] Show invite [message](https://github.com/ssbc/ssb-peer-invites#peerinvitesopeninviteinvite-cberr-data) before consuming the invite.
* Add a button in the settings view for creating a peer invite.

**Comment by Powersource** [comment]
I added the `safety` tag here because peer invites should massively reduce the rando problem.

**Comment by zicmama** [comment]
It must be from the same kind?
Runnning oasis, command 

sbotc invite.create 1
```
Trace: deprecated api used: ssb-ref.parseAddress
    at Object.parseAddress (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/ssb-ref/index.js:96:15)
    at Object.<anonymous> (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/ssb-invite/index.js:98:24)
    at apply (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/muxrpc-validation/index.js:197:15)
    at Object.<anonymous> (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/muxrpc-validation/index.js:86:14)
    at Object.hooked (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/muxrpc/stream.js:48:17)
    at PacketStream._onrequest (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/home/attilax/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/packet-stream/index.js:134:41)
```
but creates invite

**Comment by christianbundy** [comment]
If the problem is something like "onboarding is difficult because pub invites are flaky and ruin the social graph" then I agree with this issue (although I'm not married to peer invites as a solution to this problem).

**Comment by Powersource** [comment]
I don't know if I'd phrase it like that, I'd guess peer invites will be about as flaky as pub invites (although maybe a bit less over time since it's harder for pubs to get overloaded with tons of users). But I agree they ruin the social graph.

Would you merge a PR implementing this?

**Comment by christianbundy** [comment]
> Would you merge a PR implementing this?

Definitely! Sorry, my previous comment was me speaking with my contributor hat on -- as a maintainer, I'd merge anything that solves more problems than it creates.

**Comment by Powersource** [comment]
Started trying to do a bit of progress on this by adding the right plugins to flotilla, but atm stuck on this https://github.com/ssbc/ssb-peer-invites/issues/27
