### ISSUE TITLE
Error: Request must be addressed

### ISSUE THREAD

**Issue by zelfos** [fraction/oasis#431]
## What's the problem you want solved?

When I try to like a post or write a cooment or subtopic Oasis show this: Request must be addressed to 127.0.0.1 or localhost and non-GET request must contain non-blob referer.

![We browser screenshot with blank page with an error message](https://user-images.githubusercontent.com/65049678/81456687-d5fb1780-9182-11ea-9eec-b2b2f264a419.png)

In the terminal looks like this:

```bash
No referer
BadRequestError: Request must be addressed to 127.0.0.1 or localhost and non-GET requests must contain non-blob referer.
    at Object.assert (/home/user/.config/nvm/versions/node/v14.0.0/lib/node_modules/@fraction/oasis/node_modules/http-assert/index.js:8:9)
    at /home/user/.config/nvm/versions/node/v14.0.0/lib/node_modules/@fraction/oasis/src/http.js:107:9
    at dispatch (/home/user/.config/nvm/versions/node/v14.0.0/lib/node_modules/@fraction/oasis/node_modules/koa-compose/index.js:42:32)
    at /home/user/.config/nvm/versions/node/v14.0.0/lib/node_modules/@fraction/oasis/node_modules/koa-mount/index.js:52:32
    at dispatch (/home/user/.config/nvm/versions/node/v14.0.0/lib/node_modules/@fraction/oasis/node_modules/koa-compose/index.js:42:32)
    at /home/user/config/nvm/versions/node/v14.0.0/lib/node_modules/@fraction/oasis/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/home/user/.config/nvm/versions/node/v14.0.0/lib/node_modules/@fraction/oasis/node_modules/koa/lib/application.js:166:12)
    at Server.handleRequest (/home/user/.config/nvm/versions/node/v14.0.0/lib/node_modules/@fraction/oasis/node_modules/koa/lib/application.js:148:19)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:779:12)
No referer
```

This only shows up with my main account, my recently created testing account works fine and both are using the same Oasis version: 2.16.0 (I think it's the latest)

**Comment by christianbundy** [comment]
Hey! Sorry this is giving you a hard time, I know that's super frustrating.

It looks to me like you have a few extensions, are any of those disabling your HTTP referer? Could you try private browsing mode (or another browser) and check if the problem is still there?

**Comment by zelfos** [comment]
It's ok, it was only cumbersome and I realized it was my own fault and how unlikely itp s omeone to experience the same problem. You were correct, the problem was that I forgot t had the full privacy mode activated from the "Privacy Settings" extension which disables the websites,refererEnabled option in Firefox.

I'm sorry I didn't think about it before. Thanks for your answer, now this can be closed,

**Comment by christianbundy** [comment]
No problem, thanks for working through this issue with me! I'm sure someone else will have the same problem and this should be super helpful for fixing it quickly. :star2:
