### ISSUE TITLE
Error: view stream error, from:meme

### ISSUE THREAD

**Issue by zicmama** [fraction/oasis#440]
## What's the problem you want solved?

When I want to replace patchwork with oasis, this error happens

```
Error: view stream error, from:meme
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/flumedb/index.js:138:35
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-write/index.js:40:31
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-write/index.js:41:13
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-stream/throughs/async-map.js:28:19
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-cursor/skip.js:12:26
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-cursor/cursor.js:28:28
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/flumelog-offset/inject.js:43:22
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/flumelog-offset/frame/recoverable.js:48:11
  Error: past end:704578546-1882348892 < 833597399
...



RangeError: Maximum call stack size exceeded
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/flumedb/index.js:138:29
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-write/index.js:40:31
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-write/index.js:41:13
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-stream/throughs/async-map.js:28:19
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-cursor/skip.js:12:26
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/pull-cursor/cursor.js:28:28
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/flumelog-offset/inject.js:43:22
    at /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at Object.read (/home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/@fraction/oasis/node_modules/aligned-block-file/blocks.js:49:14)

```

**Comment by christianbundy** [comment]
Hi. Sorry to hear you're having trouble, that isn't fun at all. Could you add more details about what's going on here or how this is triggered? Does this error only happen in Oasis? Is it intermittent or persistent?

**Comment by zicmama** [comment]
This is persistent.
I am affraid my SSB chain is somewhere badly broken as an Oasis alone point of view.
When I run "ssb-daemon" along with oasis, it goes OK.

**Comment by christianbundy** [comment]
If you want to run Patchwork and Oasis at the same time, you need to ensure that Patchwork is started first. Are either apps working for you right now, or do they both have this error when started independently?

**Comment by zicmama** [comment]
You're right! If patchwork is started first then oasis can run. 
Thanks for solving the clue.

**Comment by christianbundy** [comment]
Are you still having the error above? Sorry, I don't think I can help debug the low-level SSB dev stuff right now.

**Comment by Powersource** [comment]
Closing this since it sounds like it might be fixed, not sure though?
