### ISSUE TITLE
ENOENT when running via podman

### ISSUE THREAD

**Issue by asymmetric** [fraction/oasis#635]
## What's the problem you want solved?

I followed the Docker instructions, while under the hood using [podman](https://podman.io/).

After bulding the image with `docker build --tag oasis --file contrib/Dockerfile  .`, I tried running it with:

```
docker run --mount type=volume,src=ssb,target=/home/node/.ssb --publish 127.0.0.0:3000:3000 --rm oasis
```

(note: I had to specify `type=volume` above)

This failed with

```
2021-03-15T14:10:19.602Z oasis No configuration file found at /home/node/.config/oasis/default.json, using built-in default values.
2021-03-15T14:10:19.603Z oasis No custom style file found at /home/node/.config/oasis/custom-style.css, ignoring this stylesheet.
2021-03-15T14:10:20.790Z oasis Listening on http://0.0.0.0:3000
/home/node/app/src/index.js:132
    throw err;
    ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://0.0.0.0:3000' ]
}
```

Worth pointing out that I'm running NixOS, and that `xdg-open` is at `/nix/store/41iyp469y2c9bpkg8rggyk2hr6w5m73z-xdg-utils-1.1.3/bin/xdg-open`.

**Comment by asymmetric** [comment]
See #647 for a port mapping fix.
