### ISSUE TITLE
Various breakage under Node 16.

### ISSUE THREAD

**Issue by jaccarmac** [fraction/oasis#688]
After updating my Node, I realized theming wasn't working. The display problems seem to be broader than that, however.

1. Switching themes has no effect. The background color is pure white and the CSS seems generally broken, though I haven't looked for specifics.
2. It is impossible to select any part of the text of a post.
3. The index bars on the settings page are blank.

There appears to be a single error generated for each page reload
```
TypeError: Cannot read property 'getFileName' of undefined
    at module.exports (/home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/node_modules/caller-path/index.js:4:40)
    at requireStyle (/home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/node_modules/require-style/index.js:17:22)
    at /home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/src/index.js:546:16
    at dispatch (/home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/node_modules/koa-compose/index.js:42:32)
    at /home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/node_modules/@koa/router/lib/router.js:372:16
    at dispatch (/home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/node_modules/koa-compose/index.js:42:32)
    at /home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/node_modules/koa-compose/index.js:34:12
    at dispatch (/home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/node_modules/@koa/router/lib/router.js:377:31)
    at dispatch (/home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/node_modules/koa-compose/index.js:42:32)
    at middleware (/home/jaccarmac/local/n/lib/node_modules/@fraction/oasis/src/index.js:1049:13)
```

I wanted to see if regenerating my indexes would help, but that option appears to be gone, even when switching back to Node 15.

**Comment by gitbenb** [comment]
Getting the same over here

**Comment by gitbenb** [comment]
What would be the ideal Node version to use with the current code, so to avoid those errors ?

**Comment by jaccarmac** [comment]
I've seen similar issues in other projects after switching to 16. So I expect this is a backward-incompatible change that people haven't prepped for yet. I haven't done the digging myself yet, or I would offer a patch.

In this case, the README suggests using the current version of Node, though, and it appears that 15 is getting phased out at the end of this month.
