### ISSUE TITLE
Error: stream is closed at /srv/export/node_modules/muxrpc/index.js:45:25

### ISSUE THREAD

**Issue by khimaros** [fraction/oasis#7]
Occasionally (approx 1/3rd of the time) when starting oasis without an external ssb-server, I encounter the following:

```
2019-08-13T00:29:18.878693990Z 2019-08-13T00:29:18.878Z koa-router GET /status
2019-08-13T00:29:18.880241814Z 
2019-08-13T00:29:18.880315568Z   Error: stream is closed
2019-08-13T00:29:18.880330756Z       at /srv/export/node_modules/muxrpc/index.js:45:25
2019-08-13T00:29:18.880338075Z       at remoteCall (/srv/export/node_modules/muxrpc/api.js:40:19)
2019-08-13T00:29:18.880344318Z       at obj.(anonymous function) (/srv/export/node_modules/muxrpc/api.js:25:18)
2019-08-13T00:29:18.880350599Z       at Promise (/srv/export/node_modules/@fraction/oasis/src/pages/models/lib/cooler.js:23:17)
2019-08-13T00:29:18.880359064Z       at new Promise (<anonymous>)
2019-08-13T00:29:18.880370308Z       at Object.get (/srv/export/node_modules/@fraction/oasis/src/pages/models/lib/cooler.js:22:12)
2019-08-13T00:29:18.880380965Z       at Object.status (/srv/export/node_modules/@fraction/oasis/src/pages/models/meta.js:19:19)
2019-08-13T00:29:18.880392648Z       at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by christianbundy** [comment]
Thanks for the bug report!

Hmm, is this just in the logs or is it breaking the `/status` page too? Very weird.

**Comment by khimaros** [comment]
It is breaking the `/status` page as well. `Internal Server Error`

**Comment by christianbundy** [comment]
And just to be clear, this is when Oasis is started with the internal or external server? I just noticed that I could trigger this by starting an external server, starting Oasis, and then killing the external server. Seems to me like maybe it was previously connected to an external server?

**Comment by khimaros** [comment]
This is when starting without an external server. The external server is never running during the lifecycle of the oasis process. Interestingly, I can see the 8008 ports open on the oasis pid, so the server is there but maybe not responsive?

**Comment by christianbundy** [comment]
I think this issue is resolved as well, could you try the latest code when you've got some free time? Thanks for all the help debugging! :crossed_fingers:

**Comment by khimaros** [comment]
cold start was successful 5/5 times, looks like this is in good shape as well!

**Comment by khimaros** [comment]
For my own education, which PR do you suspect fixed this one?

**Comment by christianbundy** [comment]
My best guess is that it came from here: https://github.com/fraction/oasis/commit/fb047f7e604289ef143cf0ce302c9f1dfe86ad2c, specifically from reordering these lines:

https://github.com/fraction/oasis/blob/fb047f7e604289ef143cf0ce302c9f1dfe86ad2c/src/pages/models/lib/cooler.js#L10-L31

There are some weird janky issues that can occur when you add one plugin before another (!), but it seems to work when I order them alphabetically *as long as ssb-db and ssb-replicate are loaded first*. There are lots of shadows bugs hidden in the ordering of [secret-stack plugins](https://github.com/ssbc/secret-stack/blob/master/PLUGINS.md). :confused:

**Comment by jedahan** [comment]
Might be related to #40
