### ISSUE TITLE
pub invites seems to be broken

### ISSUE THREAD

**Issue by gitbenb** [fraction/oasis#713]
## What's the problem you want solved?
This is the error trace I get when I try ANY of the public pub invites :

  oasis No configuration file found at /home/benb/.config/oasis/default.json, using built-in default values. +0ms
  oasis No custom style file found at /home/benb/.config/oasis/custom-style.css, ignoring this stylesheet. +2ms
  oasis Listening on http://localhost:3000 +3satten Completed in 5ms
  oasis Starting Scuttlebutt service +0msad:flatten Completed in 5ms
ssb-friends: stream legacy api usedfig:load:flatten Completed in 5ms
ssb-friends: get legacy api usedconfig:load:flatten Completed in 5ms
about-name-warmup: 16.729siming config:load:flatten Completed in 5ms
updating 6482 feeds
transpose-name-index: 13.554sng config:load:flatten Completed in 5ms
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
**TypeError: cb is not a function config:load:flatten Completed in 5ms**
    at Object.<anonymous> (/home/benb/code/oasis/node_modules/multiblob/index.js:115:16)
    at Object.<anonymous> (/home/benb/code/oasis/node_modules/ssb-blobs/inject.js:39:17)
    at Object.hooked [as size] (/home/benb/code/oasis/node_modules/hoox/index.js:10:15)
    at /home/benb/code/oasis/node_modules/multiblob-http/index.js:62:13
    at /home/benb/code/oasis/node_modules/ssb-ws/blobs.js:38:9
    at Object.want (/home/benb/code/oasis/node_modules/ssb-blobs/inject.js:363:35)
    at Object.hooked [as want] (/home/benb/code/oasis/node_modules/hoox/index.js:10:15)
    at /home/benb/code/oasis/node_modules/ssb-ws/blobs.js:37:23
    at Object.has (/home/benb/code/oasis/node_modules/ssb-blobs/inject.js:300:16)
    at Object.hooked [as has] (/home/benb/code/oasis/node_modules/hoox/index.js:10:15)

**Trace: deprecated api used: ssb-ref.parseAddressten Completed in 5ms**
    at Object.parseAddress (/home/benb/code/oasis/node_modules/ssb-ref/index.js:99:15)
    at Object.<anonymous> (/home/benb/code/oasis/node_modules/ssb-invite/index.js:204:24)
    at apply (/home/benb/code/oasis/node_modules/muxrpc-validation/index.js:197:15)
    at Object.<anonymous> (/home/benb/code/oasis/node_modules/muxrpc-validation/index.js:86:14)
    at Object.hooked (/home/benb/code/oasis/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/benb/code/oasis/node_modules/secret-stack/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/benb/code/oasis/node_modules/secret-stack/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/home/benb/code/oasis/node_modules/secret-stack/node_modules/muxrpc/stream.js:39:9)
    at PacketStream._onrequest (/home/benb/code/oasis/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/home/benb/code/oasis/node_modules/packet-stream/index.js:134:41)

[..................] | : timing config:load:flatten Completed in 5ms

The last invite code I tried, which crashed oasis altogether (from many.butt.nz) produced another bit of log that might be interesting for this issue : 

/home/benb/code/oasis/src/index.js:132:load:flatten Completed in 5ms
    throw err;
    ^

TypeError: server.gossip.add is not a function
    at /home/benb/code/oasis/node_modules/ssb-invite/index.js:272:48
    at continuation (/home/benb/code/oasis/node_modules/continuable-list/index.js:24:25)
    at /home/benb/code/oasis/node_modules/ssb-db/minimal.js:163:23
    at AsyncJobQueue.runAll (/home/benb/code/oasis/node_modules/ssb-db/util.js:207:7)
    at Object.cb (/home/benb/code/oasis/node_modules/ssb-db/minimal.js:106:15)
    at /home/benb/code/oasis/node_modules/append-batch/index.js:22:38
    at /home/benb/code/oasis/node_modules/flumelog-offset/inject.js:25:9
    at /home/benb/code/oasis/node_modules/aligned-block-file/blocks.js:172:13
    at /home/benb/code/oasis/node_modules/aligned-block-file/file.js:87:11
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
npm timing command:run-script Completed in 1319437ms
npm timing command:start Completed in 1319453ms
npm verb exit 7
npm timing npm Completed in 1319959ms
npm verb code 7

**Comment by gitbenb** [comment]
Another attempt, did not crashed oasis this time but produced a different error log trace

Error: non-error thrown: {"message":"invite not accepted","name":"Error","stack":"Error: invite not accepted\n    at /home/benb/code/oasis/node_modules/ssb-invite/index.js:249:32\n    at Object._requests.<computed> (/home/benb/code/oasis/node_modules/packet-stream/index.js:38:5)\n    at PacketStream._onrequest (/home/benb/code/oasis/node_modules/packet-stream/index.js:151:26)\n    at PacketStream.write (/home/benb/code/oasis/node_modules/packet-stream/index.js:134:41)\n    at /home/benb/code/oasis/node_modules/muxrpc/pull-weird.js:56:15\n    at /home/benb/code/oasis/node_modules/pull-stream/sinks/drain.js:24:37\n    at /home/benb/code/oasis/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11\n    at Object.cb (/home/benb/code/oasis/node_modules/packet-stream-codec/index.js:111:11)\n    at drain (/home/benb/code/oasis/node_modules/pull-reader/index.js:39:14)\n  Error: already following\n    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-invite/index.js:158:25\n    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-friends/legacy.js:85:11\n    at Object.onReady (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/layered-graph/index.js:81:22)\n    at Object.get (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-friends/legacy.js:67:15)\n    at Object.hooked [as get] (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/hoox/index.js:10:15)\n    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-invite/index.js:154:26\n    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/level-sublevel/shell.js:102:12\n    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/level-sublevel/nut.js:122:19\n    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/encoding-down/index.js:81:5"}
    at Object.onerror (/home/benb/code/oasis/node_modules/koa/lib/context.js:119:31)
    at onerror (/home/benb/code/oasis/node_modules/koa/lib/application.js:165:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    
I have tested the same invite with my manyverse ssb identity and it works just fine.
